
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-ucsborg-editpage","number":102,"title":"Luis ucsborg editpage","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/102"},{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-ucsborg-createpage","number":101,"title":"Luis ucsborg createpage","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/101"},{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-ucsborg-indexpage","number":100,"title":"Luis ucsborg indexpage","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/100"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Articles-Pages","number":99,"title":"Justin articles pages","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/99"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Article-Table","number":98,"title":"Articles Table and Test","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/98"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"WZ-MenuItemReview-table","number":83,"title":"Table Component for MenuItemReview plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/83"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"WZ-MenuItemReview-Fixtures","number":68,"title":"Create fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/68"}]
