
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBXkTqQ","is_bot":false,"login":"El-Beetor","name":"Victor Garcia"},"headRefName":"vhg-MenuItemPages","number":105,"title":"Create Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/105"},{"author":{"id":"MDQ6VXNlcjMwMDUzNTkx","is_bot":false,"login":"ChrisWoolson","name":"Chris Woolson"},"headRefName":"CW-CreatePageRecommendationRequest","number":104,"title":"Create Page to RecommendationRequest and Tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/104"}]
