
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Article-Table","number":98,"title":"Articles Table and Test","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/98"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"WZ-MenuItemReview-table","number":83,"title":"Table Component for MenuItemReview plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/83"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"WZ-MenuItemReview-Fixtures","number":68,"title":"Create fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/68"}]
