
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-ucsbOrganizationFixtures","number":72,"title":"Luis ucsb organization fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/72"},{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-CopyTeam02Files","number":71,"title":"added team02 files","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/71"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Article-Fixtures","number":70,"title":"Created Fixtures for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/70"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Articles","number":69,"title":"Copy files for Backend CRUD API Articles from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/69"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"WZ-MenuItemReview-Fixtures","number":68,"title":"Create fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/68"},{"author":{"id":"MDQ6VXNlcjMwMDUzNTkx","is_bot":false,"login":"ChrisWoolson","name":"Chris Woolson"},"headRefName":"RecommendationRequestForm","number":67,"title":"Form Component for RecommendationRequest plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/67"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"Winston-MenuItemReview-CRUD","number":66,"title":"Copy files for Backend CRUD API MenuItemReview from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-1/pull/66"}]
